# Generated by Django 2.0.6 on 2018-06-13 03:50

from django.db import migrations, models
import enumfields.fields
import postcot_core.base_types


class Migration(migrations.Migration):

    dependencies = [
        ('postcot_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='input_kind',
            field=enumfields.fields.EnumField(enum=postcot_core.base_types.AccessControlInputKind, max_length=10),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='phase',
            field=enumfields.fields.EnumField(enum=postcot_core.base_types.AccessControlPhase, max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
