"""
Django settings for postcot project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Set your own secret key by setting the POSTCOT_SECRET_KEY environment
# variable.
#
# SECURITY WARNING: keep the secret key used in production secret!
#
SECRET_KEY: str = os.environ.get('DJANGO_SECRET_KEY')
if SECRET_KEY is None or len(SECRET_KEY) == 0:
    raise AssertionError('Environment variable DJANGO_SECRET_KEY not get set.')

# Set your own allowed hosts by setting POSTCOT_ALLOWED_HOSTS environment
# variable.
#
ALLOWED_HOSTS = []
PRIMITIVE_ALLOWED_HOSTS: str = os.environ.get('POSTCOT_ALLOWED_HOSTS')
if PRIMITIVE_ALLOWED_HOSTS is not None and len(PRIMITIVE_ALLOWED_HOSTS) > 0:
    ALLOWED_HOSTS = list(PRIMITIVE_ALLOWED_HOSTS.split(', '))

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
#
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Application definition
#
INSTALLED_APPS = [
    'postcot_core.apps.PostcotCoreConfig',
    'admin_honeypot',
    'django.contrib.admin',
    'django.contrib.admindocs',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'postcot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'postcot.wsgi.application'


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
